// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trghzuzwwcvadsyqqpim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZ2h6dXp3d2N2YWRzeXFxcGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTEzNDIsImV4cCI6MjA1OTc4NzM0Mn0.TocWKqtISY3PqvRcpHYamiYpbnCFo-Tg1Hu3zQh6jfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);